version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./MedicalInfoDB:/MedicalInfoDB # Mount the MedicalInfoDB folder
    command: /MedicalInfoDB/import.sh # Execute the updated import script
  api:
    build: . # Build the API image from the Dockerfile in the current directory
    depends_on:
      - mongodb
      - mongo_seed # Ensure both MongoDB and seed are ready
    ports:
      - 80:80 # Map port 80 on host to port 80 in the container
